package in.co.everyrupee.repository.income;

import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import in.co.everyrupee.pojo.income.UserBudget;

/**
 * 
 * Repository to handle the budget for the user
 * 
 * @author Nagarjun
 *
 */
@Repository
public interface UserBudgetRepository extends JpaRepository<UserBudget, Integer> {

    /**
     * Fetch all user budget by financial portfolio id
     * 
     * @param financialPortfolioId
     * @return
     */
    List<UserBudget> findByFinancialPortfolioId(String financialPortfolioId);

    /**
     * Fetches all user with category ids specified in {@code ids} parameter
     * 
     * @param ids List of category ids
     */
    @Query("SELECT u FROM UserBudget u where u.financialPortfolioId in ?1 and u.dateMeantFor in ?2")
    List<UserBudget> fetchAllUserBudget(String financialPortfolioId, Date dateMeantFor);

    /**
     * Fetches all user with category ids specified in {@code ids} parameter
     * 
     * @param ids List of category ids
     */
    @Query("SELECT u FROM UserBudget u where u.categoryId in ?1 and u.financialPortfolioId in ?2 and u.dateMeantFor in ?3 and u.autoGeneratedBudget is true")
    List<UserBudget> fetchAutoGeneratedUserBudgetWithCategoryIds(List<Integer> categoryIds, String financialPortfolioId,
	    Date dateMeantFor);

    /**
     * Delete all user budget with category ids specified in {@code ids} parameter
     * 
     * @param ids List of category ids
     */
    @Modifying
    @Query("delete from UserBudget u where u.categoryId in ?1 and u.financialPortfolioId in ?2 and u.autoGeneratedBudget is ?3 and u.dateMeantFor in ?4")
    void deleteUserBudgetWithCategoryIds(List<Integer> categoryIds, String financialPortfolioId,
	    boolean autoGeneratedBudget, Date dateMeantFor);

    /**
     * Delete all user budget with financial portfolio id and the chosen date and
     * auto generated as true
     * 
     * @param ids List of category ids
     */
    @Modifying
    @Query("delete from UserBudget u where u.financialPortfolioId in ?1 and u.dateMeantFor in ?2 and u.autoGeneratedBudget is ?3")
    void deleteAllUserBudget(String financialPortfolioId, String dateMeantFor, boolean autoGeneratedBudget);

    /**
     * Delete all user budget with financial portfolio id and the chosen date
     * 
     * @param ids List of category ids
     */
    @Modifying
    @Query("delete from UserBudget u where u.financialPortfolioId in ?1 and u.dateMeantFor in ?2")
    void deleteAllUserBudget(String financialPortfolioId, String dateMeantFor);
}
