create database every_rupee;
use every_rupee;
CREATE  TABLE `FINANCIAL_PORTFOLIO` (
  `CUSTOMER_ID` varchar(45) NOT NULL ,
  `CASH_AVAILABLE` double NOT NULL ,
  `CREDITCARD_BALANCE` DOUBLE NOT NULL ,
  `HOME_LOAN_BALANCE` DOUBLE NOT NULL ,
  PRIMARY KEY (`CUSTOMER_ID`) )
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;