package in.co.everyrupee.service.income;

import java.util.List;

import org.springframework.util.MultiValueMap;

import in.co.everyrupee.pojo.income.UserBudget;

public interface IUserBudgetService {

    UserBudget saveUserBudget(MultiValueMap<String, String> formData, String pFinancialPortfolioId,
	    boolean autoGenerated);

    List<UserBudget> updateAutoGeneratedBudget(MultiValueMap<String, String> formData, String formFieldName,
	    String financialPortfolioId, String dateMeantFor);

    void deleteAllUserBudgets(String dateMeantFor, String financialPortfolioId, boolean autoGenerated);

    void deleteUserBudgets(String categoryIds, String financialPortfolioId, String dateMeantFor, boolean autoGenerated);

    List<UserBudget> fetchAllUserBudget(String pFinancialPortfolioId, String dateMeantFor);

    List<UserBudget> fetchUserBudgetByCategoryIds(String categoryIds, String pFinancialPortfolioId,
	    String dateMeantFor);

    void deleteUserBudgets(String categoryIds, String financialPortfolioId, String dateMeantFor);
}
