package in.co.everyrupee.pojo.income;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.PositiveOrZero;
import javax.validation.constraints.Size;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.beans.factory.annotation.Value;

import in.co.everyrupee.constants.income.DashboardConstants;

/**
 * 
 * POJO for User Budget
 * 
 * @author Nagarjun
 *
 */
@Entity
@Table(name = DashboardConstants.Budget.USER_BUDGET_TABLE)
public class UserBudget implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 234253456352089085L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = DashboardConstants.ID_SEQ)
    @SequenceGenerator(name = DashboardConstants.ID_SEQ, sequenceName = DashboardConstants.ID_SEQ, allocationSize = 100)
    @Column(name = DashboardConstants.Budget.BUDGET_ID)
    private int budgetId;

    @NotNull
    @Column(name = DashboardConstants.Budget.FINANCIAL_PORTFOLIO_ID)
    @Size(max = 60)
    private String financialPortfolioId;

    @NotNull
    @Column(name = DashboardConstants.Budget.CATEGORY_ID)
    @PositiveOrZero
    private int categoryId;

    @NotNull
    @Column(name = DashboardConstants.Budget.PLANNED)
    private double planned;

    @NotNull
    @Value("${value.autoGeneratedBudgetDefault:true}")
    @Column(name = DashboardConstants.Budget.AUTO_GENERATED_BUDGET, columnDefinition = DashboardConstants.BOOLEAN_DEFAULT_TRUE, nullable = false)
    private boolean autoGeneratedBudget;

    @NotNull
    @Column(name = DashboardConstants.Budget.DATE_MEANT_FOR)
    @Temporal(TemporalType.TIMESTAMP)
    private Date dateMeantFor;

    @CreationTimestamp
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = DashboardConstants.CREATION_DATE)
    private Date createDate;

    @UpdateTimestamp
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = DashboardConstants.MODIFICATION_DATE)
    private Date modifyDate;

    @PrePersist
    protected void onCreate() {
	if (getDateMeantFor() == null) {
	    setDateMeantFor(new Date());
	}

    }

    public int getBudgetId() {
	return budgetId;
    }

    public void setBudgetId(int budgetId) {
	this.budgetId = budgetId;
    }

    public String getFinancialPortfolioId() {
	return financialPortfolioId;
    }

    public void setFinancialPortfolioId(String financialPortfolioId) {
	this.financialPortfolioId = financialPortfolioId;
    }

    public int getCategoryId() {
	return categoryId;
    }

    public void setCategoryId(int categoryId) {
	this.categoryId = categoryId;
    }

    public double getPlanned() {
	return planned;
    }

    public void setPlanned(double planned) {
	this.planned = planned;
    }

    public Date getDateMeantFor() {
	return dateMeantFor;
    }

    public void setDateMeantFor(Date dateMeantFor) {
	this.dateMeantFor = dateMeantFor;
    }

    /**
     * @return the autoGeneratedBudget
     */
    public boolean getAutoGeneratedBudget() {
	return autoGeneratedBudget;
    }

    /**
     * @param autoGeneratedBudget the autoGeneratedBudget to set
     */
    public void setAutoGeneratedBudget(boolean autoGeneratedBudget) {
	this.autoGeneratedBudget = autoGeneratedBudget;
    }

}
