//package in.co.everyrupee.repository.income;
//
//import static org.assertj.core.api.Assertions.assertThat;
//
//import javax.persistence.PersistenceContext;
//
//import org.junit.Test;
//import org.junit.runner.RunWith;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
//import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
//import org.springframework.test.context.junit4.SpringRunner;
//
//@RunWith(SpringRunner.class)
//@DataJpaTest
//public class UserBudgetRepositoryIntegrationTest { 
//
//    @PersistenceContext   
//    TestEntityManager entityManager;
//
//    @Autowired
//    private UserBudgetRepository userBudgetRepository;
//
//    /**
//     * Assert that the injected components are not null
//     */
//    @Test
//    public void injectedComponentsAreNotNull() {
//	assertThat(entityManager).isNotNull();
//	assertThat(userBudgetRepository).isNotNull();
//    }
//
//    /**
//     * 
//     */
////    @Test
////    public void whenFindByName_thenReturnEmployee() {
////	// given
////	UserBudget userBudget = new UserBudget();
////	userBudget.setCategoryId(3);
////	userBudget.setAutoGeneratedBudget(true);
////	userBudget.setDateMeantFor(new Date());
////	userBudget.setFinancialPortfolioId("193000000000");
////	userBudget.setPlanned(300);
////	entityManager.persist(userBudget);
////	entityManager.flush();
////
////	// when
////	List<UserBudget> found = userBudgetRepository.findByFinancialPortfolioId(userBudget.getFinancialPortfolioId());
////
////	// then
////	assertThat(found.get(0).getFinancialPortfolioId()).isEqualTo(userBudget.getFinancialPortfolioId());
////    }
//}
