package in.co.everyrupee.events.listener.income;

import org.springframework.context.ApplicationListener;

import in.co.everyrupee.events.income.OnFetchCategoryTotalCompleteEvent;

/**
 * Interface for the listeners to expose the proxy (Enable Async, Create New
 * Transactions & Override Old Transactions)
 * 
 * @author Nagarjun
 *
 */
public interface IUserBudgetUpdationListener extends ApplicationListener<OnFetchCategoryTotalCompleteEvent> {

    public void updateAutoGeneratedUserBudget(final OnFetchCategoryTotalCompleteEvent event);
}
