package in.co.everyrupee.controller.income;

import static org.hamcrest.CoreMatchers.is;
import static org.mockito.Mockito.when;
import static org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers.springSecurity;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

import in.co.everyrupee.pojo.income.UserBudget;
import in.co.everyrupee.service.income.UserBudgetService;

/**
 * User Budget Controller Test
 * 
 * @author Nagarjun
 *
 */
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public class UserBudgetControllerTest {

    @Autowired
    private WebApplicationContext context;

    private MockMvc mvc;

    @MockBean
    private UserBudgetService userBudgetService;

    @Before
    public void setUp() {
	mvc = MockMvcBuilders.webAppContextSetup(context).apply(springSecurity()).build();
    }

    /**
     * Get user Budget by financial portfolio Id test
     * 
     * @throws Exception
     */
    @WithMockUser(value = "spring")
    @Test
    public void getUserBudgetByFinancialPortfolioId() throws Exception {
	String financialPortfolioId = "193000000";
	String dateMeantFor = "01062019";
	UserBudget userBudget = new UserBudget();
	List<UserBudget> userBudgetList = new ArrayList<UserBudget>();

	userBudget.setFinancialPortfolioId(financialPortfolioId);
	userBudget.setCategoryId(3);
	userBudget.setPlanned(300);
	userBudget.setAutoGeneratedBudget(true);

	userBudgetList.add(userBudget);

	when(this.userBudgetService.fetchAllUserBudget(financialPortfolioId, dateMeantFor)).thenReturn(userBudgetList);

	this.mvc.perform(get("/api/budget/193000000?dateMeantFor=01062019").contentType(MediaType.APPLICATION_JSON))
		.andDo(print()).andExpect(status().isOk()).andExpect(jsonPath("$.*").isNotEmpty())
		.andExpect(jsonPath("$[0].financialPortfolioId", is(financialPortfolioId)));
    }
}
