package in.co.everyrupee.controller.income;

import static org.hamcrest.CoreMatchers.is;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers.springSecurity;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.RequestBuilder;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

import in.co.everyrupee.constants.income.DashboardConstants;
import in.co.everyrupee.pojo.income.UserBudget;
import in.co.everyrupee.repository.income.UserBudgetRepository;
import in.co.everyrupee.service.income.UserBudgetService;

/**
 * User Budget Controller Test
 * 
 * @author Nagarjun
 *
 */
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public class UserBudgetControllerIntegrationTest {

    @Autowired
    private WebApplicationContext context;

    private MockMvc mvc;

    @Autowired
    private UserBudgetService userBudgetService;

    @MockBean
    private UserBudgetRepository userBudgetRepository;

    Logger logger = LoggerFactory.getLogger(this.getClass());

    private Date dateMeantFor;

    private List<Integer> categoryIdList;

    private List<UserBudget> userBudgetList;

    private String financialPortfolioId;

    @Before
    public void setUp() {
	setUserBudgetList(new ArrayList<UserBudget>());
	UserBudget userBudget = new UserBudget();

	setMvc(MockMvcBuilders.webAppContextSetup(context).apply(springSecurity()).build());
	DateFormat format = new SimpleDateFormat(DashboardConstants.DATE_FORMAT, Locale.ENGLISH);

	try {
	    setDateMeantFor(format.parse("01062019"));
	} catch (ParseException e) {
	    logger.error(e + " Unable to add date to the user budget");
	}

	// Set Category Id List
	setCategoryIdList(new ArrayList<Integer>());
	getCategoryIdList().add(3);
	getCategoryIdList().add(4);
	getCategoryIdList().add(5);
	getCategoryIdList().add(6);

	// Sets financial portfolio id
	setFinancialPortfolioId("193000000");

	// sets a user budget for user budget list
	userBudget.setFinancialPortfolioId(getFinancialPortfolioId());
	userBudget.setCategoryId(3);
	userBudget.setPlanned(300);
	userBudget.setAutoGeneratedBudget(true);

	// Appends the above created user budget to the list
	getUserBudgetList().add(userBudget);

    }

    /**
     * TEST: Get user Budget by financial portfolio Id
     * 
     * @throws Exception
     */
    @WithMockUser(value = "spring")
    @Test
    public void getUserBudgetByFinancialPortfolioId() throws Exception {

	when(getUserBudgetRepository().fetchAllUserBudget(getFinancialPortfolioId(), getDateMeantFor()))
		.thenReturn(getUserBudgetList());

	getMvc().perform(get("/api/budget/193000000?dateMeantFor=01062019").contentType(MediaType.APPLICATION_JSON))
		.andExpect(status().isOk()).andExpect(jsonPath("$.*").isNotEmpty())
		.andExpect(jsonPath("$[0].financialPortfolioId", is(getFinancialPortfolioId())));

	verify(getUserBudgetRepository(), times(1)).fetchAllUserBudget(getFinancialPortfolioId(), getDateMeantFor());
    }

    /**
     * TEST: Delete user Budget by category Id
     * 
     * @throws Exception
     */
    @WithMockUser(value = "spring")
    @Test
    public void deleteAutoGeneratedUserBudgetById() throws Exception {

	getMvc().perform(
		delete("/api/budget/193000000/3,4,5,6?dateMeantFor=01062019").contentType(MediaType.APPLICATION_JSON))
		.andExpect(status().isOk()).andExpect(jsonPath("$.*").isNotEmpty())
		.andExpect(jsonPath("$.message", is("success")));

	verify(getUserBudgetRepository(), times(1)).deleteAutoGeneratedUserBudgetWithCategoryIds(getCategoryIdList(),
		getFinancialPortfolioId(), getDateMeantFor());
    }

    /**
     * TEST: Delete all entries from user Budget with financial portfolio id as
     * ${id}
     * 
     * @throws Exception
     */
    @WithMockUser(value = "spring")
    @Test
    public void deleteAllUserBudgetById() throws Exception {

	// Autogenerated true
	getMvc().perform(delete("/api/budget/193000000?dateMeantFor=01062019&autoGenerated=true")
		.contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.*").isNotEmpty()).andExpect(jsonPath("$.message", is("success")));

	verify(getUserBudgetRepository(), times(1)).deleteAllUserBudget(getFinancialPortfolioId(), getDateMeantFor(),
		true);

	// Autogenerated false
	getMvc().perform(delete("/api/budget/193000000?dateMeantFor=01062019&autoGenerated=false")
		.contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.*").isNotEmpty()).andExpect(jsonPath("$.message", is("success")));

	verify(getUserBudgetRepository(), times(1)).deleteAllUserBudget(getFinancialPortfolioId(), getDateMeantFor());
    }

    /**
     * TEST: update user Budget by category Id without form data (Internal Server
     * Error)
     * 
     * @throws Exception
     */
    @WithMockUser(value = "spring")
    @Test
    public void updateAutoGeneratedUserBudgetById() throws Exception {

	String pDateMeantFor = "01062019";

	RequestBuilder request = MockMvcRequestBuilders.post("/api/budget/193000000/update/autoGenerated")
		.param(DashboardConstants.Budget.DATE_MEANT_FOR, pDateMeantFor).accept(MediaType.APPLICATION_JSON)
		.contentType(MediaType.APPLICATION_FORM_URLENCODED_VALUE);

	when(getUserBudgetRepository().fetchAutoGeneratedUserBudgetWithCategoryIds(getCategoryIdList(),
		getFinancialPortfolioId(), getDateMeantFor())).thenReturn(getUserBudgetList());

	getMvc().perform(request).andExpect(status().isInternalServerError());
    }

    /**
     * TEST: save user Budget by category Id
     * 
     * @throws Exception
     */
    @WithMockUser(value = "spring")
    @Test
    public void update() throws Exception {

	List<Integer> categoryList = new ArrayList<Integer>();
	categoryList.add(3);

	RequestBuilder request = MockMvcRequestBuilders.post("/api/budget/save/193000000")
		.accept(MediaType.APPLICATION_JSON).param(DashboardConstants.Budget.PLANNED, "300")
		.param(DashboardConstants.Budget.CATEGORY_ID, "3")
		.param(DashboardConstants.Budget.FINANCIAL_PORTFOLIO_ID, getFinancialPortfolioId())
		.param(DashboardConstants.Budget.DATE_MEANT_FOR, "01062019")
		.contentType(MediaType.APPLICATION_FORM_URLENCODED_VALUE);

	when(getUserBudgetRepository().fetchAutoGeneratedUserBudgetWithCategoryIds(getCategoryIdList(),
		getFinancialPortfolioId(), getDateMeantFor())).thenReturn(getUserBudgetList());

	getMvc().perform(request).andExpect(status().isOk());

	verify(getUserBudgetRepository(), times(1)).fetchAutoGeneratedUserBudgetWithCategoryIds(categoryList,
		getFinancialPortfolioId(), getDateMeantFor());

    }

    /**
     * TEST: Get user Budget by financial portfolio Id (Exception)
     * 
     * @throws Exception
     */
    @Test
    public void getUserBudgetByFinancialPortfolioIdException() throws Exception {

	getMvc().perform(get("/api/budget/193000000?dateMeantFor=01062019").contentType(MediaType.APPLICATION_JSON))
		.andExpect(status().isUnauthorized());

	verify(getUserBudgetRepository(), times(0)).fetchAllUserBudget(getFinancialPortfolioId(), getDateMeantFor());
    }

    /**
     * TEST: Delete user Budget by category Id (EXCEPTION)
     * 
     * @throws Exception
     */
    @Test
    public void deleteAutoGeneratedUserBudgetByIdException() throws Exception {

	getMvc().perform(
		delete("/api/budget/193000000/3,4,5,6?dateMeantFor=01062019").contentType(MediaType.APPLICATION_JSON))
		.andExpect(status().isUnauthorized()).andExpect(jsonPath("$.error", is("Unauthorized")));

	verify(getUserBudgetRepository(), times(0)).deleteAutoGeneratedUserBudgetWithCategoryIds(getCategoryIdList(),
		getFinancialPortfolioId(), getDateMeantFor());
    }

    /**
     * TEST: Delete all entries from user Budget with financial portfolio id as
     * ${id}
     * 
     * @throws Exception
     */
    @Test
    public void deleteAllUserBudgetByIdException() throws Exception {

	// Autogenerated true
	getMvc().perform(delete("/api/budget/193000000?dateMeantFor=01062019&autoGenerated=true")
		.contentType(MediaType.APPLICATION_JSON)).andExpect(status().isUnauthorized())
		.andExpect(jsonPath("$.error", is("Unauthorized")));

	verify(getUserBudgetRepository(), times(0)).deleteAllUserBudget(getFinancialPortfolioId(), getDateMeantFor(),
		true);

	// Autogenerated false
	getMvc().perform(delete("/api/budget/193000000?dateMeantFor=01062019&autoGenerated=false")
		.contentType(MediaType.APPLICATION_JSON)).andExpect(status().isUnauthorized())
		.andExpect(jsonPath("$.error", is("Unauthorized")));

	verify(getUserBudgetRepository(), times(0)).deleteAllUserBudget(getFinancialPortfolioId(), getDateMeantFor(),
		false);
    }

    /**
     * TEST: update user Budget by category Id (Exception)
     * 
     * @throws Exception
     */
    @Test
    public void updateAutoGeneratedUserBudgetByIdException() throws Exception {

	String pDateMeantFor = "01062019";

	RequestBuilder request = MockMvcRequestBuilders.post("/api/budget/193000000/update/autoGenerated")
		.param(DashboardConstants.Budget.DATE_MEANT_FOR, pDateMeantFor).param("2", "300").param("3", "400")
		.accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_FORM_URLENCODED_VALUE);

	getMvc().perform(request).andExpect(status().isUnauthorized());

	when(getUserBudgetRepository().fetchAutoGeneratedUserBudgetWithCategoryIds(getCategoryIdList(),
		getFinancialPortfolioId(), getDateMeantFor())).thenReturn(getUserBudgetList());

	verify(getUserBudgetRepository(), times(0)).fetchAutoGeneratedUserBudgetWithCategoryIds(getCategoryIdList(),
		getFinancialPortfolioId(), getDateMeantFor());

	verify(getUserBudgetRepository(), times(0)).saveAll(getUserBudgetList());
    }

    public UserBudgetRepository getUserBudgetRepository() {
	return userBudgetRepository;
    }

    public void setUserBudgetRepository(UserBudgetRepository userBudgetRepository) {
	this.userBudgetRepository = userBudgetRepository;
    }

    public Date getDateMeantFor() {
	return dateMeantFor;
    }

    public void setDateMeantFor(Date dateMeantFor) {
	this.dateMeantFor = dateMeantFor;
    }

    public List<Integer> getCategoryIdList() {
	return categoryIdList;
    }

    public void setCategoryIdList(List<Integer> categoryIdList) {
	this.categoryIdList = categoryIdList;
    }

    public List<UserBudget> getUserBudgetList() {
	return userBudgetList;
    }

    public void setUserBudgetList(List<UserBudget> userBudgetList) {
	this.userBudgetList = userBudgetList;
    }

    public UserBudgetService getUserBudgetService() {
	return userBudgetService;
    }

    public void setUserBudgetService(UserBudgetService userBudgetService) {
	this.userBudgetService = userBudgetService;
    }

    public String getFinancialPortfolioId() {
	return financialPortfolioId;
    }

    public void setFinancialPortfolioId(String financialPortfolioId) {
	this.financialPortfolioId = financialPortfolioId;
    }

    public MockMvc getMvc() {
	return mvc;
    }

    public void setMvc(MockMvc mvc) {
	this.mvc = mvc;
    }

}
